language: objective-c

before_install:
    - rvm use system
    - sudo gem install cocoapods -v '0.39.0'

osx_image: xcode7.2

script:
    xctool -workspace EasyDownloadSession.xcworkspace -scheme EasyDownloadSessio build -sdk iphonesimulator
